# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9133f286edd5a0696f2abd7ec63e34c7239db8bd445fa7a297f8b5081efa9b9f8c2f504914128ddeb38916e7328fbb792d68b04cce1d7fc0cd7fad85dbe1de9

test:
  secret_key_base: 0f23cdfc329e6a1e906a2e6690480770933d6b3bc95a14f20d1fd4b7e83f798d86c113848d867daf71ffc8d260be9940ad2d8a17b82b7ff2b3f691da4bb4b264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
